### ISSUE TITLE
What is the recommended approach for initializing the Client with a specific site

### ISSUE THREAD

**Issue by chiefanku** [recurly/recurly-client-java#145]
Most (if not all) of the [V3 API ](https://developers.recurly.com/api/v2021-02-25/index.html )calls require passing a `site-id`. However the java client does not seem to have a way to set the site-id for requests
https://github.com/recurly/recurly-client-java/blob/v3-v2021-02-25/src/main/java/com/recurly/v3/Client.java

Is this is a known issue? What is the workaround or how do you specify a site for the java client;

**Comment by douglasmiller** [comment]
Thank you for reporting this, @chiefanku.

Fortunately, this is only a documentation issue. There is no requirement to pass a `site_id` with any of the requests. The site information is determined via the `apiKey` that is passed to the constructor of the `Client` (which you linked). 

I'll make sure that this oversight in the documentation is fixed ASAP!

**Comment by chiefanku** [comment]
@douglasmiller thanks for your prompt response and clarification. I had already gone through Recurly support and they also kept referring me to the documentation which was wrong. My underlying issue remains unsolved though and I will post as a separate question

**Comment by douglasmiller** [comment]
@chiefanku what is the underlying issue that you are experiencing? How to configure the client sdk to communicate with a particular site?

If so, this is managed by the `apiKey` that is passed into the constructor of the `Client`. You would set the value to the private api key obtained from the recurly.com web portal.

I've re-opened this issue for you.

**Comment by douglasmiller** [comment]
Ah I see that you had a different issue: https://github.com/recurly/recurly-client-java/issues/146. Re-closing :)
